INSERT INTO StartwellDB.CrossReference (SurveyID_Customer,QuesID_Customer,SurveyID_Provider,QuesID_Provider) VALUES ('1', '1', '2', '1');
INSERT INTO StartwellDB.CrossReference(SurveyID_Customer,QuesID_Customer,SurveyID_Provider,QuesID_Provider) VALUES ('1', '2', '2', '2');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1', '3', '2', '3');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1', '4',' 2','4');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1','5','2','5');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1','6','2','6');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1','7','2','7');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1', '8', '2', '8');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1','9','2','9');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1','10','2','10');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1','11','2','11');
INSERT INTO StartwellDB.  CrossReference (  SurveyID_Customer, QuesID_Customer, SurveyID_Provider, QuesID_Provider) VALUES ('1', '12', '2','12');
